### ISSUE TITLE
Add option to update user languages

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-bulk-user-admin#13]
It would be great if it also had an option to update user languages.

**Comment by leekelleher** [comment]
@bjarnef Thanks, it's a great idea!

**Comment by jamiepollock** [comment]
@leekelleher I can look at this later on tonight (8pm+ your time) if you'd like. I'm also free most of tomorrow too.

**Comment by jamiepollock** [comment]
@leekelleher @bjarnef afraid I've hit a bit of a snag with support of Languages with versions of Umbraco prior to 7.2.2. In 7.2.2+ the Umbraco ServiceContext uses the [ILocalizedTextService](https://github.com/umbraco/Umbraco-CMS/blob/release-7.2.2/src/Umbraco.Core/Services/ILocalizedTextService.cs). Which has the `GetSupportedCultures()` function.

Although this isn't used in the [EditUser.aspx.cs until 7.3.0](https://github.com/umbraco/Umbraco-CMS/blob/release-7.3.0/src/Umbraco.Web/umbraco.presentation/umbraco/users/EditUser.aspx.cs#L113). 

In any case we might consider a minimum dependency version bump to 7.2.2, unless you want to go down the old school root of [grabbing the languages like they do in 7.2.0](https://github.com/umbraco/Umbraco-CMS/blob/release-7.2.0/src/Umbraco.Web/umbraco.presentation/umbraco/users/EditUser.aspx.cs#L111-L118) -> 7.2.8.

If we go down the upgrade version route then we it seems the `GetSupportedCultures()` function sort of does this [in a round about sorta way](https://github.com/umbraco/Umbraco-CMS/blob/release-7.2.2/src/Umbraco.Core/Services/LocalizedTextService.cs).

Sorry for the information overload just want to get all the facts before we make a big decision like this.

**Comment by leekelleher** [comment]
@jamiepollock Don't worry, it's not info overload at all. All good.  If you want to bump up the minimum support Umbraco version, that's cool. (The NuGet package restrictions would prevent future me from accidentally updating to it 😉)

If we do bump the minimum version, I'd say we go all the way to vLatest (v7.5.4) ... then we can make use of the newer Angular directives too (re: #12)

**Comment by bjarnef** [comment]
@jamiepollock @leekelleher for the localization stuff v7.3+ would be great (because language files can be included in the package file and probably also safe to use the newer localization service).
For the new UI Angular directives/components v7.4+ should be sufficient :-)

**Comment by jamiepollock** [comment]
Thanks @bjarnef!

What do you think @leekelleher? 7.5 or 7.4? I think I'm edging more towards 7.5 because of any potential UI tweaks. Lots we still have a version that supports versions prior to that on nuget now.

**Comment by leekelleher** [comment]
@jamiepollock Go with v7.5x latest 👍

**Comment by jamiepollock** [comment]
@leekelleher right you are, skipper! So will we go with 7.5.0 or 7.5.4 as the dependency? I'm guessing the latter.

I'll resume work on this again this morning.

**Comment by leekelleher** [comment]
@jamiepollock Yup, go latest 👍

**Comment by jamiepollock** [comment]
@leekelleher disregard my last message... still waking up.

**Comment by jamiepollock** [comment]
@leekelleher @bjarnef okay, we're all good to go on the [feature/modify-user-language](https://github.com/leekelleher/umbraco-bulk-user-admin/tree/feature/modify-user-language)!

Have a look at what you think, and leave any notes. I'm going a leave a note for yourself @leekelleher about one of the bits of code, but feel free to test this out. I've tested this on a sandbox instance of Umbraco 7.5.4 (which is required now we're at requirement of Umbraco.Core 7.5.4).

**Comment by jamiepollock** [comment]
Once we get this one cleared, I'll take a look at the other feature requests :)

**Comment by leekelleher** [comment]
Closing this issue, as a pull-request has been opened. Any discussion (about the implementation) can be done on #16.
