### ISSUE TITLE
Check mark is not green

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-bulk-user-admin#14]
The checkmark icon (active state) has a class `green`, but is actually not green. Use `color-green` instead :)
You could use `color-red` for the disabled state as well and maybe change markup to the following:

```
<i class="icon" ng-class="{ 'icon-check color-green': user.Active, 'icon-delete color-red': !user.Active }"></i>
```

Furthermore the icon is flicking a bit when hovering, because of this in core.

```
.umb-listview .table-striped tbody i:not(.handle):hover {
    display: none!important;
}
```

Previously I excluded "handle" in listview because it was flickering like this - it think the reason why it original hide `i` i listview was because of when changing between a checkbox and "icon-check" on selection in listview. I think the should be changed to should icons by default and then hide specific icons or just toggle a "hidden" class.

**Comment by leekelleher** [comment]
Closing this issue. Any discussion about the implementation can be done on #17 😃
