### ISSUE TITLE
Add filters on columns

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-bulk-user-admin#15]
At the moment you can filter the listview via search and for "active" columns by writing "is:active" or "is:inactive".

Could it instead has a filter like memberlistview?
https://our.umbraco.org/projects/backoffice-extensions/memberlistview-for-umbraco-7/

E.g. to filter by columns not shown in listview, e.g. by "Disable Umbraco Access" ... or maybe users who has access to a specific section?

**Comment by leekelleher** [comment]
@bjarnef Sounds cool, (to have custom filters) and useful.  I'm not too keen on having a side panel to set the filters, I did like the inline nature of what we have now.  But totally open to discussion about that.

**Comment by bjarnef** [comment]
Yes, just thinking it might not be intuitive to editors unless they know it (or has to remember it).
Unlike members, users don't have custom properties, so it could use dropdowns like this example http://www.angularjs4u.com/demos/angularjs-drop-filter/

But for 3+ filters it might be better to use the side panel.

**Comment by leekelleher** [comment]
Closing this ticket, as I'm archiving the project.
