### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by jameskimsca** [leekelleher/umbraco-bulk-user-admin#19]
Umbraco 7.6.3
BulkUserAdmin 0.3.0

I've created a pull request for this here:
https://github.com/leekelleher/umbraco-bulk-user-admin/pull/18

What did you do?
Sorted dashboard column and tried to traverse to another page via the pagination links

What did you expect to happen?
The table displays the second set of data sorted by the column initially actioned upon

What actually happened?
Links didn't work with a javascript error

**Comment by leekelleher** [comment]
@jameskimsca Thanks for spotting this and sending a pull-request.

I'll close of this ticket and we'll review on PR #18.
