### ISSUE TITLE
Adding in UserType to dashboard table

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-bulk-user-admin#2]
Hey guys,
Already done the leg work for this. Having what user type a user is would be really helpful as the apps I have in mind have multiple users.

The goal is make another ticket where users can filter or sort by pre-existing fields (Name, Email, Active and of course User Type).

Thanks,
Jamie

**Comment by mattbrailsford** [comment]
Sound good to me

**Comment by jamiepollock** [comment]
All sorted!
