### ISSUE TITLE
Allow Filter & Sorting of dashboard table data

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-bulk-user-admin#3]
As referenced in Ticket #2.

I know this isn't an easy one, sorting by table headers is something Umbraco has in it's toolbox somewhere, I've not had much joy re-purposing this for my own backoffice tables.

I'd ideally also like to add in filters by User Type, so I can apply a bulk action to a specific user type (eg. Disable all Editors)

What do you think?

**Comment by leekelleher** [comment]
_Sorry, I thought I replied to this yesterday, but I mustn't have hit submit._

I dig the idea :+1: Not sure on how it would be implemented, but like you say, Umbraco should have a similar pattern in its toolbox

**Comment by jamiepollock** [comment]
no worries @leekelleher. Sorting I'm 30% sure I can see if we can repurpose the Umbraco list view. Although working with it via GitHub search is a lesson in patience. The key is to get the right look at feel so it's not different from that component, getting the UX right is important here.

As for filtering, I'd probably make a new API call and update the list view. This personally makes more sense than doing the same thing via JS based on existing results.

**Comment by jamiepollock** [comment]
Part 1: Sorting now in as a PR #5 :)

**Comment by jamiepollock** [comment]
@leekelleher should have said. I'll wait until PR #5 is complete before submitting a PR for filtering. I probably should have split these into two separate tickets.

**Comment by leekelleher** [comment]
@jamiepollock No worries at all, feel free to open a separate ticker for filtering.  Is PR #5 ready to ship? :shipit:

**Comment by jamiepollock** [comment]
@leekelleher yep, I'm happy with it :)

I'll open up a new ticket for filtering, are you available to have a sanity check on what I should be filtering on? I have some time this morning to get started on this.

**Comment by leekelleher** [comment]
@jamiepollock Cool, I'll look to merge it in today.

re: filtering, sure, happy to sanity check.

**Comment by jamiepollock** [comment]
awesome, [new ticket created](https://github.com/leekelleher/umbraco-bulk-user-admin/issues/6) :)

**Comment by jamiepollock** [comment]
Closing this ticket off as the discussion is now in a new ticket. Plus sorting got merged :)
