### ISSUE TITLE
Allow Filter of dashboard table data

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-bulk-user-admin#6]
As mentioned in #3, this is a separate ticket to discuss just filtering of the dashboard table data.

Initial thoughts are to have:
1. A free text search field which allows backoffice users to search against Name & Email
2. A checkbox list bound against user types to filter in or out users of specific types
3. [Optional - stretch goal] Checkbox for whether a user is active or not

**Comment by leekelleher** [comment]
I guess I was only thinking about a free text search, similar to the native List View filter. Where it would filter by the column values.

I'm not sure how much I'd use the checkboxes to filter out user-types, but I'm not against the idea.

**Comment by jamiepollock** [comment]
@leekelleher that sounds logical. 

For me having the ability to filter out non-admin users or users in a specific group would be useful. We have a site which has a lot of one specific user type and it would be nice to use the tool to bulk lockout these users.

I could start with just a text search and then go from there? Concerned adding any more than that would be a big change code & UX wise.

**Comment by leekelleher** [comment]
re: filtering user-types / checkboxes - Unless we have "power filters" such as `is:admin` in the free-text? (It's similar to how GitHub do `is:issue` or `is:pr` in their search/filters)

**Comment by jamiepollock** [comment]
I like that idea. Users doesn't have any Lucene search behind it so all of this will be done in linq after getting the initial GetUsers() call.

I'm still thinking power filters will a stretch goal and I'd definitely want to put tests around that because we'd be writing our own parsing for it.

**Comment by jamiepollock** [comment]
Just thinking 

> I guess I was only thinking about a free text search, similar to the native List View filter. Where it would filter by the column values.

| Name | Email | User Type | Active |
| --- | --- | --- | --- |
| Foo | foo@bar.com | Adminstrators | X |
| Bar | bar@foo.com | Editor |  |
| Wolf | hello@wolf.com | Editor | X |

Searching Administrators would bring back

| Name | Email | User Type | Active |
| --- | --- | --- | --- |
| Foo | foo@bar.com | Adminstrators | X |

Searching Foo would bring back

| Name | Email | User Type | Active |
| --- | --- | --- | --- |
| Foo | foo@bar.com | Adminstrators | X |
| Bar | bar@foo.com | Editor |  |

We could still do that without power filters but I'd be more inclined to have a power filter like `usertype:Adminstrators` or `email:foo` and then have a default search too.

**Comment by leekelleher** [comment]
Both PRs are now merged in! :tada: Thanks @jamiepollock! :tada:

**Comment by jamiepollock** [comment]
@leekelleher cheers Lee. I guess next step is updating the readme.md with a new screenshot and brief description about filtering.

**Comment by leekelleher** [comment]
Yeah, I'm happy to update the screengrab... as I need to pixelate out all the personal info.

**Comment by jamiepollock** [comment]
okay, I can provide some blurb about the filter too. Something like...

> ## Filtering
> 
> All columns can be filtered using the search box. Name, Email & User Type can be searched via partial match.
> 
> User active status can be filtered by searching "active" or "inactive".

**Comment by leekelleher** [comment]
Ace. Let's open a new issue/topic to discuss the README or user-guide/docs :+1:

**Comment by jamiepollock** [comment]
Agreed! :)
