### ISSUE TITLE
Updated documentation

### ISSUE THREAD

**Issue by jamiepollock** [leekelleher/umbraco-bulk-user-admin#8]
Now that we've added a few more bits of functionality the readme.md / docs/*.md could do with updating.

Tasks 
- [x] Update screenshot
- [x] Add blurb about filtering
- [x] Possibly discuss sorting?

Anything else to be included and documented below.

**Comment by jamiepollock** [comment]
Probably best to discuss how/where to proceed with docs. I don't think we need a full blown docs folder as there's not much to discuss but feel free to correct my judgement, @leekelleher ;)

**Comment by leekelleher** [comment]
Guess it's whether we want a longer README, or separate it off to files the /docs folder?

At the moment, I'm happy with a longer README. But then I did think that we could add a screengrab of the side-panel to show how the actual bulk update part works.

@jamiepollock If you have time and want to make a start on updating the README, feel free to make a new branch in the repo, then we can both work on it.

**Comment by jamiepollock** [comment]
@leekelleher I'll be honest, I'm not entirely sure how to proceed. At the moment I'm just posing as a person who might know how to work with people on github ;)

Now that I'm a contributor do I create a branch in this repo rather than creating a PR?

**Comment by leekelleher** [comment]
@jamiepollock No worries at all, it's all a learning curve :+1:

The way we do it on Ditto is that we clone the main repository, and create a new branch on our local clone. (Naming it something relative, but can be whatever.) We push that branch up to the main repo, then GitHub will display a "create a PR" button.  So you can create a PR within the same repo.

Does that make sense?  We can jump on a [Gitter chat](https://gitter.im/leekelleher) if it's easier?

**Comment by jamiepollock** [comment]
Sort of, I guess the part that is unclear is pushing the branch to the main repo. I'll jump on Gitter too.

**Comment by mattbrailsford** [comment]
Animated gift screencast?

**Comment by leekelleher** [comment]
@mattbrailsford Trying to remember the name of some screencapture animated gif software I used to use...  _hey, shouldn't you be on holiday?!_ :wink:

**Comment by mattbrailsford** [comment]
I've used LICEcap before which is OK. And yea, I am 😎🌞🏖

**Comment by leekelleher** [comment]
@mattbrailsford LICEcap, yes! that's the one - thanks! :beers:

**Comment by jamiepollock** [comment]
@leekelleher @mattbrailsford had to google "LICEcap" clearly it's screen capture software but it also sounds like a preventative measure against mites that infest hair :P

**Comment by leekelleher** [comment]
Closing this one, in preparation for v0.3.0 release.
